# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'openedx-aspects'
  description: "Open edX Aspects Learner Analytics."
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/arch-interest-groups: "bmtcril,feanil"
spec:

  # (Required) This can be a group(`group:<group_name>` or a user(`user:<github_username>`)
  owner: user:bmtcril

  # (Required) Acceptable Type Values: service, website, library
  type: 'reference'

  # (Required) Acceptable Lifecycle Values: experimental, production, deprecated
  lifecycle: 'production'
