# CSV backend configuration
# #########################
backend: csv_file
# This can be anything smart_open can handle, a local directory or
# an S3 bucket, etc., but importing to ClickHouse only supports S3 right now
# https://pypi.org/project/smart-open/

# The next two lines point to the same place, but each needs a different URL
# format.
csv_output_destination: s3://openedx-aspects-loadtest/logs/large_test/
s3_source_location: https://openedx-aspects-loadtest.s3.amazonaws.com/logs/large_test/
csv_load_from_s3_after: true

# ClickHouse Backend configuration
# ################################
db_host: localhost
db_port: 8443
db_name: xapi_lt
db_event_sink_name: event_sink
db_username: ch_admin
db_password: test
s3_key: ...
s3_secret: ...

# Run options
log_dir: logs
num_batches: 3
batch_size: 100

# Overall start and end date for the entire run
start_date: 2014-01-01
end_date: 2023-11-27

# All courses will be this long, and be fit into the start / end dates
# This must be less than end_date - start_date days.
course_length_days: 120

# The size of the test
num_organizations: 3
num_actors: 10

# How many of each size course to create. The sum of these is the total number
# of courses created for the test.
num_course_sizes:
  small: 1
  medium: 1
  large: 1
  huge: 1

# Course size configurations, how many of each type of object are created for
# each course of this size. "actors" must be less than or equal to "num_actors".
# For a course of this size to be created it needs to exist both here and in
# "num_course_sizes".
course_size_makeup:
  small:
    actors: 5
    problems: 20
    videos: 10
    chapters: 3
    sequences: 10
    verticals: 20
    forum_posts: 20
  medium:
    actors: 7
    problems: 40
    videos: 20
    chapters: 4
    sequences: 20
    verticals: 30
    forum_posts: 40
  large:
    actors: 10
    problems: 80
    videos: 30
    chapters: 5
    sequences: 40
    verticals: 80
    forum_posts: 200
  huge:
    actors: 10
    problems: 160
    videos: 40
    chapters: 10
    sequences: 50
    verticals: 100
    forum_posts: 1000
